config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  scope "(:locale)", locale: /en|vi/ do 
    resources :books do 
      resources :reviews
    end
    root "books#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews
  validates :title, presence: true, length: { maximum: 255 }
  validates :author, presence: true, length: { maximum: 255 }
  validates :description, presence: true

  has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "100x100>" }, 
    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale
  
  private
    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

    def default_url_options
      {
        locale: I18n.locale
      }
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    if params[:category].blank?
      @books = Book.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @books = Book.where(category_id: @category_id).order("created_at DESC")
    end
  end
 
  def show
    if @book.reviews.blank? 
      @average_review = 0
    else
      @average_review  = @book.reviews.average(:rating).round(2)
    end
  end 

  def new
    @book = current_user.books.build
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def create 
    @book = current_user.books.build book_params
    @book.category_id = params[:category_id]
    if @book.save
      flash[:success] = t(".book_created")
      redirect_to root_path
    else
      render :new 
    end
  end

  def edit
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def update
    @book.category_id = params[:category_id]
    if @book.update book_params
      flash[:success] = t(".book_updated")
      redirect_to book_path(@book)
    else
      render :edit 
    end
  end

  def destroy
    @book.destroy
    flash[:info] = t(".book_deleted")
    redirect_to root_path
  end

  private

    def book_params
      params.require(:book).permit :title, :description, :author, :category_id,
        :book_img
    end

    def find_book
      @book = Book.find params[:id]
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new review_params
    @review.book_id = @book.id
    @review.user_id = current_user.id
    
    if @review.save
      redirect_to book_path(@book)
    else
      render :new 
    end
  end
  
  def edit
  end

  def update
    if @review.update review_params
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to book_path(@book)
  end

  private
    def review_params
      params.require(:review).permit :rating, :comment
    end

    def find_book
      @book = Book.find params[:book_id]
    end

    def find_review
      @review = Review.find params[:id]
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title =""
    base_title = "Đánh Giá Sách"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= form_for @book, html: { multipart: true } do |f| %>
  <%= render "shared/error_messages" %>
  <%= select_tag(:category_id, options_for_select(@categories),
    prompt: "Select a category") %>

  <div class="field mt-3">
    <%= f.file_field :book_img %>
  </div>
  
  <div class="field mt-3">
    <%= f.label :title, t(".title"), class: "text-info" %>
    <%= f.text_field :title, placeholder: t(".title"), class: "form-control" %>
  </div>

  <div class="field mt-3">
    <%= f.label :description, t(".description"), class: "text-info" %>
    <%= f.text_area :description, placeholder: t(".description"),
      class: "form-control" %>
  </div>
  
  <div class="field mt-3">
    <%= f.label :author, t(".author"), class: "text-info" %>
    <%= f.text_field :author, placeholder: t(".author"), 
      class: "form-control" %>
  </div>

  <div class="field mt-3">
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  </div>
 
<% end %>

app/views/books/edit.html.erb
<div class="col-md-6 offset-md-3">
  <div class="edit-book-form">
    <% provide :button_text, t(".edit_book") %>

    <%= form_for @book, html: { multipart: true } do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.select :category_id, @categories %>
      <div class="field mt-3">
        <%= f.file_field :book_img %>
      </div>
      
      <div class="field mt-3">
        <%= f.label :title, t(".title"), class: "text-info" %>
        <%= f.text_field :title, placeholder: t(".title"), class: "form-control" %>
      </div>

      <div class="field mt-3">
        <%= f.label :description, t(".description"), class: "text-info" %>
        <%= f.text_area :description, placeholder: t(".description"),
          class: "form-control" %>
      </div>
      
      <div class="field mt-3">
        <%= f.label :author, t(".author"), class: "text-info" %>
        <%= f.text_field :author, placeholder: t(".author"), 
          class: "form-control" %>
      </div>

      <div class="field mt-3">
        <%= f.submit yield(:button_text), class: "btn btn-primary" %>
      </div>
     
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @books.count == 0 %>
  <h1><%= t(".the_are_no") %></h1>
<% else %>
  <div class="row">
    <%= @books.each do |book| %>
      <div class="col-md-3">
        <a href="/books/<%= book.id %>">
          <%= image_tag book.book_img.url(:book_index), class: "book" %>
        </a>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/new.html.erb
<div class="col-md-6 offset-md-3">
  <div class="new-book-form">
    <% provide :button_text, t(".create_book") %>

    <h1>New book</h1>

    <%= render "form" %>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @book.book_img.url(:book_show), class: "book-show" %>
  </div>
  <div class="col-md-8">
    <div class="book-info">
      <h2 class="book-title"><%= @book.title %></h2>
      <h3 class="book-author"><span>From</span><%= @book.author %></h3>
      <h2 class="avg-rating">Average Rating</h2>
      <div class="average-review-rating" data-score=<%= @average_review %>></div>
      <span class="number-of-reviews">Based on <%= @book.reviews.count %> reviews</span>
      <p class="book-decription"><%= @book.description %></p>
    </div> 
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="reviews">
       <!-- Where the reviews/ratings will go -->
      <h1>Reviews</h1>
      <%= render @book.reviews %>
      <div> 
        <%= link_to "Add Review", new_book_review_path(@book), 
          class: "btn-custom" %>
      </div>
    </div>
  </div>
</div>
<div class="links btn-group mt-3 mb-5">
  <%= link_to t(".back"), root_path, class: "btn btn-custom" %>
  <% if user_signed_in? %>
    <% if @book.user_id == current_user.id %>
      <%= link_to t(".edit"), edit_book_path(@book), class: "btn btn-custom" %>
      <%= link_to t(".delete"), book_path(@book), method: :delete, 
        data: { confirm: t(".are_you_sure")}, class: "btn btn-custom" %>
    <% end %>
  <% end %>
</div>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to t(".book_reviews"), root_path, 
        class: "navbar-brand text-muted" %>
    </div>

    <ul class="nav mr-auto">
      <% if user_signed_in? %>
        <li>
          <%= link_to t(".log_out"), destroy_user_session_path, 
          method: :delete, class: "text-muted" %>
        </li>
      <% else %>
        <li class="mr-3">
          <%= link_to t(".sign_up"), new_user_registration_path,  
            class: "text-muted" %>
        </li>
        <li>
          <%= link_to t(".log_in"), new_user_session_path, 
            class: "text-muted" %>
        </li>
      <% end %>
    </ul>
    
    <ul class="nav">
      <li class="dropdown mr-5">
        <a href="#" class="dropdown-toggle text-muted" data-toggle="dropdown" 
          role="button" aria-expended="false"><%= t(".category") %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% Category.all.each do |category| %>
            <li class="<%= 'active' if params[:category] == category.name %>">
              <%= link_to category.name, books_path(category: category.name), 
                class: "link text-secondary" %>
            </li>
          <% end %>
        </ul>
      </li>

      <% if user_signed_in? %>
        <li>
          <%= link_to t(".add_book"), new_book_path, class: "text-muted" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav> 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", 
      "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container mt-2">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([@book, @book.reviews.build]) do |f| %>

  <div id="rating-form" class="field">
    <%= f.label :rating %>
  </div>
  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment, class: "form-control" %>
  </div>
  
  <div class="field mt-3">
    <%= f.submit "Create comment", class: "btn btn-custom" %>
  </div>
  
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <div class="review-rating" data-score="<%= review.rating %>"></div>
  <p class="review-comment"><%= review.comment %></p>

  <% if user_signed_in? %> 
    <% if review.user_id == current_user.id %>
      <div class="links btn-group">
        <%= link_to "Edit", edit_book_review_path(review.book, review), 
          class: "btn btn-custom" %>
        <%= link_to "Delete", book_review_path(review.book, review), 
          method: :delete, data: { confirm: "Are you sure? " }, 
          class: "btn btn-custom" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 offset-md-3">
  <div class="new-review-form">
    <h2>Edit Review</h2>

    <%= render "form" %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="col-md-6 offset-md-3">
  <div class="new-review-form">
    <h1>New Review</h1>

    <%= render "form" %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @book.errors.any? %>
  <div class="row">
    <div class="col-md-12">
        <%= t(".the_form_contains") %> 
        <%= pluralize(@book.errors.count, t(".error") )%>.
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li class="text-danger"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>